### ISSUE TITLE
Create user hashing scheme

### ISSUE THREAD

**Issue by hannahcoonley** [GatechVIP/gatech-swapr-server-node#6]
for @scott-s-douglas

**Comment by scott-s-douglas** [comment]
We're going to just use a SHA-1 hash to go from username -> id. username lives only in the id_map table, and the anonymous id is used everywhere else.

**Comment by scott-s-douglas** [comment]
Actually, after consultation with some Facebook folks, I think an autoincrementing integer for the id is just fine. Facebook does just that for their own users (but then hashes the ids after 30 days for some reason which my contact didn't know).

Ultimately the point is that if an attacker is in a position to enumerate all the user ids in our database, then we've got much bigger problems than the fact that our user ids are easy to enumerate.
